apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-persistent-volume
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: ~/kubernetes-training/Volumes/data