apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: myapp-sc
  namespace: myapp-ns
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: io1
  iopsPerGB: "10"
  fsType: ext4