apiVersion: v1
kind: Service
metadata:
    name: my-cluster-ip
spec:
    selector:
        app: nginx-app
    type: ClusterIP
    ports:
    - name: http
      port: 80
      targetPort: 80 
      protocol: TCP