apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-volume
  labels:
    name: daemon-volume
spec:
  selector:
    matchLabels:
      name: daemon-volume
  template:
    metadata:
      labels:
        name: daemon-volume
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - name: volume
          mountPath: "/mnt/data"
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: my-pvc
