apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
spec:
  completions: 3
  parallelism: 2
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["echo", "Kubernetes Job"]
      restartPolicy: Never