apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: nginx
  labels:
    name: nginx
spec:
    - host: nginx.manda.com
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx-service
              servicePort: 80