apiVersion: apps/v1
kind: Deployment
metadata:
  name: volumes-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-vol
  template:
    metadata:
      labels:
        app: gke-vol
    spec:
      containers:
      - name: test-container
        image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      volumes:
        - name: cache-volume
          emptyDir: {}